### ISSUE TITLE
clean up

### ISSUE THREAD

**Issue by celeroncoder** [coderKrysio/knock-with-next#11]
Clean up the code and try finding why did u made that mistake

- [x] No need to put this in state as they are not changing and are static, put them out of the Functional Component.
```ts
  const [userData1, setUserData1] = useState({
    cuid: "cljijrahe00003h6fpiwtcjp1",
    name: "coderKrysio",
    email: "coderKrysio@gmail.com",
  })

  const [userData2, setUserData2] = useState({
    cuid: "cljiobki200013h6fn0zpcj6t",
    name: "anushree",
    email: "anushreejaiswal.srn@gmail.com",
  })
```

- [x] The dependency array is filled up of thing that doesn't change.
  
  ```ts
    useEffect(() => {
      KnockAPI.setIdentify(userData1)
      KnockAPI.getUser(userData1.cuid)
      KnockAPI.setIdentify(userData2)
      KnockAPI.getUser(userData2.cuid)
    },[userData1.cuid, userData2.cuid, userData1, userData2])
  ```

- [x] And What's the point of the `useEffect` here?
- [x] Why are u using the `getUser` function when you're not using its returned value, if it's for testing comment it after you are done.

- [ ] Don't use `any` type unless absolutely necessary, what's the point of using typescript then if you are not defining types?
  ```ts
    const DisplayUser = ({
      userData,
      recipientId
     }:any) => {
  ```

- [x] Try using prettier or any other code formatter so that code can be used by others
    ```ts
    <button
      disabled={message === ""}
      className="border-2 border-black rounded-lg p-2 my-2"
      >Send</button>
    ```

**Comment by coderKrysio** [comment]
5/6 done
without using any type the values of the props are coming to be undefined

**Comment by celeroncoder** [comment]
> 5/6 done without using any type the values of the props are coming to be undefined

You can create an issue of the tasks so that would be better to track your progress, so do that...
